export { default as AddPlacePage } from './AddPlacePage'
export { default as AdminPage } from './AdminPage'
export { default as AllMyPlacesPage } from './AllMyPlacesPage'
// export { default as DeletePlace } from './/DeletePlace'
export { default as EditPlacePage } from './EditPlacePage'
export { default as ErrorPage } from './ErrorPage'
export { default as LandingPage } from './LandingPage'
export { default as LoginPage } from './LoginPage'
export { default as MyStatsPage } from './MyStatsPage'
export { default as OthersActivityPage } from './OthersActivityPage'
export { default as ProfilePage } from './ProfilePage'
export { default as RegisterPage } from './RegisterPage'
export { default as TrendsPage } from './TrendsPage'
export { default as LayoutPage } from './LayoutPage'
